#!/usr/bin/env bash
# Configures local host resolution
cp /etc/hosts /tmp/hosts_new
sed -i 's/127.0.0.1/127.0.0.2/g' /tmp/hosts_new
cat /tmp/hosts_new > /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
